# Generated by Django 3.0.7 on 2020-07-09 06:13

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('enroll_number', models.CharField(max_length=20)),
                ('tenth_board', models.IntegerField()),
                ('tenth_roll_number', models.CharField(max_length=50)),
                ('tenth_cent', models.CharField(max_length=10)),
                ('twelfth_board', models.IntegerField()),
                ('twelfth_roll_number', models.CharField(max_length=50)),
                ('twelfth_cent', models.CharField(max_length=10)),
                ('pet_roll_number', models.CharField(max_length=30)),
                ('pet_rank', models.CharField(max_length=8)),
                ('father_first', models.CharField(max_length=30)),
                ('father_last', models.CharField(max_length=30)),
                ('father_job', models.CharField(max_length=30)),
                ('father_phone', models.CharField(max_length=30)),
                ('mother_first', models.CharField(max_length=30)),
                ('mother_last', models.CharField(max_length=30)),
                ('mother_job', models.CharField(max_length=30)),
                ('mother_phone', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('aadhar_number', models.CharField(max_length=30)),
            ],
        ),
    ]
