# Generated by Django 3.0.7 on 2020-07-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200711_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
