# Generated by Django 3.0.7 on 2020-07-11 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_student', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('enroll_number', models.CharField(max_length=20)),
                ('tenth_board', models.IntegerField()),
                ('tenth_roll_number', models.CharField(max_length=50)),
                ('tenth_cent', models.CharField(max_length=10)),
                ('twelfth_board', models.IntegerField()),
                ('twelfth_roll_number', models.CharField(max_length=50)),
                ('twelfth_cent', models.CharField(max_length=10)),
                ('pet_roll_number', models.CharField(max_length=30)),
                ('pet_rank', models.CharField(max_length=8)),
                ('father_first', models.CharField(max_length=30)),
                ('father_last', models.CharField(max_length=30)),
                ('father_job', models.CharField(max_length=30)),
                ('father_phone', models.CharField(max_length=30)),
                ('mother_first', models.CharField(max_length=30)),
                ('mother_last', models.CharField(max_length=30)),
                ('mother_job', models.CharField(max_length=30)),
                ('mother_phone', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('aadhar_number', models.CharField(max_length=30)),
            ],
        ),
    ]
