# Generated by Django 3.0.7 on 2020-07-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200711_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default='NA', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='enroll_number',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_first',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='father_job',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='father_last',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='student',
            name='is_faculty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_first',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_job',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_last',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='pet_rank',
            field=models.CharField(default='NA', max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='pet_roll_number',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='NA', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_board',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_cent',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_roll_number',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_board',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_cent',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_roll_number',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.IntegerField(default=-1),
        ),
    ]
