# Generated by Django 3.0.7 on 2020-07-11 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_auto_20200711_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Student',
        ),
    ]
