# Generated by Django 3.0.7 on 2020-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200711_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='tenth_board',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='twelfth_board',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
