# Generated by Django 3.0.7 on 2020-07-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200711_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grad_year',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
